# this is an example configuration

tags = [ "rando-projects", "school", "art" ]

use_due_dates = [ false, true, false ]

[weights]
mon = [ 0.1, 0.7, 0.2 ]
tue = [ 0.2, 0.7, 0.1 ]
wed = [ 0.1, 0.7, 0.2 ]
thu = [ 0.2, 0.6, 0.2 ]
fri = [ 0.3, 0.5, 0.2 ]
sat = [ 0.2, 0.3, 0.5 ]
sun = [ 0.5, 0.2, 0.3 ]
