# this is an example configuration

# path to the task file
task_filepath = "/home/luak/projects/git/rusty-manager/example/tasks"

# put tags for each assignment. Order dictates the rest
tags = [ "rando-projects", "schoolwork", "personal" ]

# boolean to indicate if we should use due dates to weight the assignments
## when 'true' assignments due earlier will have a higher probability of 
## being pulled. When 'false' equal weight to all assignments
use_due_dates = [ false, true, false ]


# weights for each tag project are broken down by day of the week.
## i.e. if you have two tags: ["schoolwork", "personal"] and weights
## on monday are given as [0.8, 0.2] then a new assignment from the
## schoolwork tag will be given with 80% probability, and a new one
## from the homework tag will be given with 20% probability
[weights]
mon = [ 0.1, 0.7, 0.2 ]
tue = [ 0.2, 0.7, 0.1 ]
wed = [ 0.1, 0.7, 0.2 ]
thu = [ 0.2, 0.6, 0.2 ]
fri = [ 0.3, 0.5, 0.2 ]
sat = [ 0.2, 0.3, 0.5 ]
sun = [ 0.5, 0.2, 0.3 ]
