[package]
name = "rusty-krab-manager"
version = "0.1.0"
authors = ["luak <arya_kaul@g.harvard.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
chrono = "0.4"
tui = "0.5"
termion = "1.5"
config = "0.9"
rodio = "0.10"
dirs = "2.0"
